---
- name: Grub config settings
  copy:
    src: grub/default
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
    # TODO: add console= and resume=, if they work

- name: Update Grub
  command: update-grub
