---
- name: spotify repo key
  apt_key:
          keyserver: hkp://keyserver.ubuntu.com:80
          id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
          state: present

- name: spotify repo
  apt_repository:
          repo: deb http://repository.spotify.com stable non-free
          state: present

- name: install spotify pkgs
  apt: name={{item}} state=installed
  with_items:
          - spotify-client
